### ISSUE TITLE
运行时无任何响应

### ISSUE THREAD

**Issue by brk3d** [gumblex/trustedsleepbot#2]
使用系统:Fedora 32
Python 版本：3.8.5
运行文件:tsleepd.py
使用telegram-cli:https://snapcraft.io/telegram-cli 1.4.5
配置telegram-cli路径:/var/lib/snapd/snap/bin/telegram-cli
症状：无任何响应
strace调试显示程序无任何操作
pdb调试显示当程序运行至874行便无响应
请问是什么问题呢，谢谢

**Comment by gumblex** [comment]
一般来说就是 tg-cli 卡了。目前 tg-cli 已经不再更新，已经积累了很多问题；本项目也不再维护。请寻找其他替代方案。

**Comment by brk3d** [comment]
您好，我想重新运行此项目，求把telegram 的@TrustedSleepBot 注销让我重新注册这个用户名23333

**Comment by brk3d** [comment]
谢谢啦
